#!/bin/bash
# Check Docker permissions on server

echo "🔍 Checking Docker permissions for justin user..."
echo ""
echo "Run this command to check if justin can use Docker without sudo:"
echo ""
echo "ssh justin@147.182.236.230 'docker ps'"
echo ""
echo "If it shows 'permission denied', run these commands ON THE SERVER:"
echo ""
echo "# 1. Add justin to docker group:"
echo "sudo usermod -aG docker justin"
echo ""
echo "# 2. Apply the change (choose one):"
echo "# Option A: Restart Docker service"
echo "sudo systemctl restart docker"
echo ""
echo "# Option B: Log out and back in"
echo "exit"
echo "ssh justin@147.182.236.230"
echo ""
echo "# 3. Verify it works:"
echo "docker ps"
echo ""
echo "If you still need sudo, add passwordless sudo for Docker:"
echo "echo 'justin ALL=(ALL) NOPASSWD: /usr/bin/docker' | sudo tee /etc/sudoers.d/justin-docker"