#!/bin/bash
# Fix port 80 conflict on server

echo "🔍 Checking what's using port 80 on the server..."
echo ""
echo "Run these commands on your server:"
echo ""
echo "ssh justin@147.182.236.230"
echo ""
echo "# Check what's using port 80:"
echo "sudo lsof -i :80"
echo ""
echo "# Or check Docker containers:"
echo "docker ps --format 'table {{.Names}}\t{{.Ports}}'"
echo ""
echo "# If another Docker container is using port 80, stop it:"
echo "docker stop <container_name>"
echo ""
echo "# If it's nginx or apache:"
echo "sudo systemctl stop nginx"
echo "# or"
echo "sudo systemctl stop apache2"
echo ""
echo "# Then manually start our container:"
echo "docker run -d --name agenticdev-app --restart unless-stopped -p 80:80 -v /data:/data --env-file /home/justin/.env agenticdev:latest"
echo ""
echo "# Or use port 8080 if you need port 80 for something else:"
echo "docker run -d --name agenticdev-app --restart unless-stopped -p 8080:80 -v /data:/data --env-file /home/justin/.env agenticdev:latest"
echo ""
echo "# Then update your domain to proxy from port 8080 if needed"